spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: dbmain

  shell:
    interactive:
      enabled: true
      #enabled: false
    noninteractive:
      enabled: false

    command:
      version:
        enabled: false

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    root: INFO

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2